### ISSUE TITLE
Can not Start the Game

### ISSUE THREAD

**Issue by diegoforni** [stratosphereips/NetSecGame#268]
On a fresh install of main, python3 -m AIDojoCoordinator.worlds.NSEGameCoordinator does not work
```
python3 -m AIDojoCoordinator.worlds.NSEGameCoordinator 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/diegoforni/Documents/labsin/NetSecGame-main/AIDojoCoordinator/worlds/NSEGameCoordinator.py", line 13, in <module>
    from AIDojoCoordinator.coordinator import GameCoordinator
  File "/Users/diegoforni/Documents/labsin/NetSecGame-main/AIDojoCoordinator/coordinator.py", line 9, in <module>
    from AIDojoCoordinator.utils.utils import observation_as_dict, get_str_hash, ConfigParser
  File "/Users/diegoforni/Documents/labsin/NetSecGame-main/AIDojoCoordinator/utils/utils.py", line 7, in <module>
    from AIDojoCoordinator.scenarios import scenario_configuration
  File "/Users/diegoforni/Documents/labsin/NetSecGame-main/AIDojoCoordinator/scenarios/scenario_configuration.py", line 30, in <module>
    cyst_cfg.PassiveServiceConfig(
  File "<@beartype(cyst.api.configuration.host.service.PassiveServiceConfig.__init__) at 0x12c9d74c0>", line 330, in __init__
TypeError: PassiveServiceConfig.__init__() got an unexpected keyword argument 'name'

```

**Comment by eldraco** [comment]
done?

**Comment by ondrej-lukas** [comment]
Solved with the private repo. I'm keeping this open until we fix for good

**Comment by harpomaxx** [comment]
The issue persists in main. I will reopen it , since it is not actually fixed

**Comment by harpomaxx** [comment]
I managed to create a hotfix for the issue you have reported. We have a temporary private mirror of the cyst-core repository which you have read access to.  To make sure this works, the order of the steps has to be followed

1. create venv for aidojo and activate it
2. git clone the NetSecGame repository
3. install the package pip install -e . from the root directory
4. git clone the https://github.com/stratosphereips/tmp-cyst-core
5. install the package locally pip3 install -e ./tmp-cyst-core/  (this MUST happen after the instalation of Coordinator)
6. intall the correct version of the netaddr pip3 install netaddr==1.3.0 (this MUST happen after the installation of cyst-core)

Can you pls try it ? I've tested in the fresh env and it seems to be working for me. When the new version of cyst-core is published as package, everything should work without the last 2 points. Sorry for the mess (edited)
